config/urls.py
'''
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
'''
from django.views import defaults as default_views
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from tasks.views import *
from tasks.reports import * 

from tasks.apiviews import *

from django.contrib.auth.views import LogoutView

from rest_framework.routers import SimpleRouter
from rest_framework_nested import routers

router = routers.SimpleRouter()

router.register(r"api/task",TaskViewSet)

history_router = routers.NestedSimpleRouter(router, r'api/task', lookup='task')
history_router.register(r'history', TaskHistoryViewSet)

router.register("api/history",TaskHistoryViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),

    path('', GenericTaskView.as_view()),

    #user management
    path('user/login', UserLoginView.as_view()),
    path('user/signup', UserCreateView.as_view()),
    path('user/logout', LogoutView.as_view()),
    
    #tasks
    path('tasks',GenericTaskView.as_view()),
    path('create-task', GenericTaskCreateView.as_view()),
    path('update-task/<pk>', GenericTaskUpdateView.as_view()),
    path('reports/<pk>', GenericReportUpdateView.as_view()),

    path('delete-task/<pk>', GenericTaskDeleteView.as_view()),
] + router.urls + history_router.urls


'''
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("task_manager.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

'''

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tasks/models.py
from django.db import models

#from django.contrib.auth.models import User

from task_manager.users.models import User

from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save

from datetime import datetime, timezone

STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("IN_PROGRESS", "IN_PROGRESS"),
    ("COMPLETED", "COMPLETED"),
    ("CANCELLED", "CANCELLED"),
)

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False) #dont think we need this after adding the status column
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User , on_delete=models.CASCADE , null=True,blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    priority = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class TaskHistory(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE,null=True,blank=True)
    old_status = models.CharField(max_length=100, choices=STATUS_CHOICES)
    new_status = models.CharField(max_length=100, choices=STATUS_CHOICES)
    date_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.task)

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True, blank = True)
    timing = models.IntegerField(default = 0)
    last_report = models.DateTimeField(null=True, default=datetime.now(timezone.utc).replace(hour=0))

    def __str__(self):
        return f"{str(self.user)} : {str(self.timing)}" 

@receiver(pre_save, sender=Task)
def generateHistory(instance, **kwargs):
    try:
        task = Task.objects.get(pk=instance.id)
    except:
        task = None

    if task is not None and task.status != instance.status:
        TaskHistory.objects.create(
            task=task,
            old_status=task.status,
            new_status=instance.status
        )

@receiver(post_save, sender=User)
def generateReport(instance, **kwargs):
    try:
        user = User.objects.get(pk=instance.id)
        try:
            report = Report.objects.get(user=user)
        except:
            report = None
    except:
        user = None
        report = None

    if user is not None and report is None:
        Report.objects.create(
            user=user,
            timing=0
        )

@receiver(post_save, sender=Report)
def setReportTime(instance, **kwargs):
    try:
        report = Report.objects.get(pk=instance.id)
    except:
        report = None

    if report is not None:
        report.last_report = datetime.now(timezone.utc).replace(hour=report.timing)
        report.save()

tasks/views.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from django.forms import ModelForm, ValidationError

from tasks.models import Task, TaskHistory, Report, User

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView

from django.contrib.auth.mixins import LoginRequiredMixin

#User Views

class AuthorizedTaskManager(LoginRequiredMixin):
    def get_queryset(self):
        return Task.objects.filter(deleted=False, user=self.request.user)

class UserLoginView(LoginView):
    template_name = "user_login.html"


class StyledUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(StyledUserCreationForm, self).__init__(*args, **kwargs)

        input_styling = "p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black"

        self.fields['username'].widget.attrs.update({'class' : input_styling})
        self.fields['password1'].widget.attrs.update({'class' : input_styling})
        self.fields['password2'].widget.attrs.update({'class' : input_styling})
    

class UserCreateView(CreateView):
    form_class = StyledUserCreationForm
    template_name = "user_create.html"
    success_url = "/user/login"

#Task Views

class GenericTaskView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(deleted=False, completed=False)
    template_name = "tasks.html"
    context_object_name = "tasks"
    #paginate_by = 5 #not specified in milestone

    def get_queryset(self):
        search_term = self.request.GET.get("search")
        list_type = self.request.GET.get("type")

        if list_type == 'pending':
            tasks = Task.objects.filter(deleted=False, completed=False, user=self.request.user).order_by('priority')
        elif list_type == 'completed':
            tasks = Task.objects.filter(deleted=False, completed=True, user=self.request.user).order_by('priority')
        else :
            tasks = Task.objects.filter(deleted=False, user=self.request.user).order_by('priority')
        if search_term:
            tasks = tasks.filter(title__icontains=search_term)
        return tasks

    def get_context_data(self):
        context = {"tasks" : self.get_queryset()}
        context['completed_tasks'] = Task.objects.filter(deleted=False, completed=True, user=self.request.user).count()
        context['total_tasks'] = Task.objects.filter(deleted=False, user=self.request.user).count()
        context['report_id'] = Report.objects.get(user=self.request.user).id
        return context


class GenericTaskDeleteView(AuthorizedTaskManager, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = "/tasks"

class TaskCreateForm(ModelForm):

    def clean_title(self):
        title = self.cleaned_data["title"]
        if(len(title) < 3):
            raise ValidationError("Your Title should have more than 3 characters")
        return title

    class Meta:
        model = Task
        fields = ["title","description","priority","completed","status"]
    
    def __init__(self, *args, **kwargs):
       super(TaskCreateForm, self).__init__(*args, **kwargs)

       input_styling = "p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black"

       self.fields['title'].widget.attrs.update({'class' : input_styling})
       self.fields['description'].widget.attrs.update({'class' : f'{input_styling} h-[150px]'})
       self.fields['priority'].widget.attrs.update({'class' : input_styling})
       self.fields['completed'].widget.attrs.update({'class' : 'form-check-input appearance-none h-6 w-6 border border-gray-200 rounded bg-gray-200 checked:bg-red-600 checked:border-red-600 focus:outline-none transition align-top bg-no-repeat bg-center bg-contain cursor-pointer block text-black'})

class GenericTaskUpdateView(AuthorizedTaskManager, UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "task_update.html"
    success_url = "/tasks"

    def form_valid(self, form):
        if 'priority' in form.changed_data:
            form_priority = form.cleaned_data['priority']
            checkPriority(form_priority, self.request.user)

        '''
        if 'status' in form.changed_data:
            new_status = form.cleaned_data['status']
            pr_key = self.object.pk

            this_task = Task.objects.get(id=pr_key)
            old_status = this_task.status

            hist = TaskHistory(task = this_task, old_status = old_status, new_status = new_status)
            hist.save()
        '''

        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

class GenericTaskCreateView(CreateView):
    form_class = TaskCreateForm
    template_name = "task_create.html"
    success_url = "/tasks"

    def form_valid(self, form):

        #check and append all priorities
        form_priority = form.cleaned_data['priority']

        checkPriority(form_priority, self.request.user)

        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

def checkPriority(priority_num, user_a):
    has_issue = True
    p_i = priority_num
    to_change = []

    while(has_issue):
        #check if there is a task with priority
        print(f"Checking for priority {p_i}")
        try:
            model = Task.objects.get(priority=p_i,deleted=False,completed=False,user=user_a)
            to_change.append(model)
        except Task.DoesNotExist:
            has_issue = False
            print(f"There is no task with this priority")

        p_i += 1

    for i in range(len(to_change)):
        obj = to_change[i]
        print(f"Old Priority = {obj.priority}")
        obj.priority = int(obj.priority) + 1
        print(f"New Priority = {obj.priority}")

    if(len(to_change) > 0):
        Task.objects.bulk_update(to_change, ['priority'])

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <script src="https://cdn.tailwindcss.com"></script>
<script src="https://kit.fontawesome.com/642123ab45.js" crossorigin="anonymous"></script>
        <title>
            {% block title %}Task Manager{% endblock %}
        </title>
        <style>
            p,li{
                font-size: 0.75rem;
                line-height: 1rem;
                color: gray;
            }
            label{
                font-size: 1.125rem;
                line-height: 1.75rem;
                display: inline-block;
                color: black;
                margin-top: 1rem;
            }
            .errorlist{
                color: red !important;
                list-style-type: none;
                background: rgb(255, 169, 169);
                display: block;
                border-radius: 5px;
                padding: 20px;
                margin-top: 30px;
                
                margin-bottom: 10px;
            }
        </style>
    </head>
    <body>
        <div class="flex justify-center w-full">
            <div class="w-[340px] m-20">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

templates/report_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update Task{% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Report Settings
    </div>
    <br>
    <br>
    <form method="post" class="tasks-form">
        <p>
            <label for="id_timing">At what hour would you like to recieve task reports?:</label>
            <input type="number" name="timing" value="{{form.timing.value}}" min="0" max="23" class="p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black" required id="id_timing">
        </p>
        {% csrf_token %}
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Update
        </button>
    </form>
{% endblock %}

templates/task_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Task{% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Create Todo
    </div>
    <br>
    <br>
    <form method="post" class="tasks-form">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Add
        </button>
    </form>
{% endblock %}

templates/task_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Delete Task {{object.title}} {% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Delete {{object.title}}
    </div>
    <br>
    <br>
    <form method="post">
        {% csrf_token %}
        <span class="text-xl">
            Are you sure you want to delete "{{object.title}}"? You can not undo this.
        </span>
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Confirm
        </button>
    </form>
{% endblock %}

templates/task_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update Task{% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Update Todo
    </div>
    <br>
    <br>
    <form method="post" class="tasks-form">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Update
        </button>
    </form>
{% endblock %}

templates/tasks.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Todo Manager{% endblock %} 

{% block content %}
    <div class="flex items-center justify-between">
        <span class="text-4xl font-bold">
            Hi {{request.user}}
        </span>
        <a href="user/logout" class="text-red-400">
            Log out
        </a>
    </div>
    <div class="text-gray-400 my-3">
        {{completed_tasks}} of {{total_tasks}} tasks completed
    </div>
    <div class="mb-3">
        <a class="t-list-butt cursor-pointer py-1 px-6 rounded-3xl inline-block {% if request.GET.type != 'completed' and request.GET.type != 'pending' %} text-red-400 bg-red-100 {% endif %}" btype="all" href="?type=all">
            All
        </a>
        <a class="t-list-butt cursor-pointer py-1 px-6 rounded-3xl inline-block m-1 {% if request.GET.type == 'pending' %} text-red-400 bg-red-100 {% endif %}" btype="pending" href="?type=pending">
            Pending
        </a>
        <a class="t-list-butt cursor-pointer py-1 px-6 rounded-3xl inline-block m-1 {% if request.GET.type == 'completed' %} text-red-400 bg-red-100 {% endif %}" btype="completed" href="?type=completed">
            Completed
        </a>
    </div>
    {% for task in tasks %}
        <div task-block class="bg-slate-100 rounded-lg p-3 flex justify-between items-center mb-5 task-complete-{{task.completed}}">
            <div class="flex">
                <div class="ml-2">
                    <a class="font-bold {% if task.completed == True %} line-through text-red-400 {% endif %}">
                        {{task.title}}  <span class="text-gray-400">&middot; {{task.priority}}</span>
                    </a>
                    <br>
                    <span class="text-gray-500 text-sm">
                        {{task.created_date | date:"D d M"}}
                    </span>
                </div>
            </div>
           <div>
                    <a href="/update-task/{{task.id}}" class="bg-green-600 hover:bg-green-500 m-0.5 text-white rounded-lg inline-flex items-center justify-center w-[38px] h-[38px]" title="Edit">
                    <i class="fa-solid fa-pen"></i>
                    </a>
                    <a href="/delete-task/{{task.id}}" class="bg-red-600 hover:bg-red-500 m-0.5 text-white rounded-lg inline-flex items-center justify-center w-[38px] h-[38px]" title="Delete">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </div> class="fal fa-trash"></i>
                </a>
            </div>
        </div>
    {% endfor %}
    <a href="create-task" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-10 text-center">
        Add
    </a>
    <br>
    <a href="reports/{{report_id}}" class="text-red-500 block text-center">
        Report Settings
    </a>

{% endblock %}

templates/user_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Todo Manager
    </div>
    <br>
    <br>
    <div class="text-2xl">
        Signup
    </div>
    <br>
    <form method="post" class="tasks-form">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Sign Up
        </button>
        <br>
        <a href="login" class="text-sm text-red-500 block text-center">
            Already have an account?
        </a>
    </form>
{% endblock %}

templates/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %} 

{% block content %}
    <div class="text-4xl font-bold">
        Todo Manager
    </div>
    <br>
    <br>
    <div class="text-2xl">
        Login
    </div>
    <br>
    <form method="post" class="tasks-form">
        {{ form.non_field_errors }}
        <p>
            {{ form.username.errors }}
            <label for="id_username">Username:</label>
            <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username" class="p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black">
        </p>
        <p>
            {{ form.password.errors }}
            <label for="id_password">Password:</label>
            <input type="password" name="password" autocomplete="current-password" required id="id_password" class="p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black">
        </p>
        {% csrf_token %}
        <button type="submit" class="bg-red-500 block hover:bg-red-600 text-white rounded-xl p-3 text-base cursor-pointer transition w-full mt-4">
            Login
        </button>
    </form>
    
    <br>
    <a href="signup" class="text-sm text-red-500 block text-center">
        Create an account
    </a>
{% endblock %}